version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgres://hjkaqzts:8aALgvqCK73ZB5kwVp6TY1EPxGuNGXx5@mahmud.db.elephantsql.com/hjkaqzts'
      NODE_ENV: development
      PORT: 4000
    ports:
      - "3200:4000"
    networks:
      - wor

networks:
  wor:
    driver: bridge